name: Build Morphe Patch Package

on:
  push:
    paths:
      - 'morphe-patches/**'
      - '.github/workflows/build-morphe-patch.yml'
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-mpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission for Gradlew
        run: |
          if [ -f "morphe-patches/gradlew" ]; then
            chmod +x morphe-patches/gradlew
          fi

      - name: Build Morphe Patch Package (.mpp)
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd morphe-patches && gradle build

      - name: Upload .mpp Artifact
        uses: actions/upload-artifact@v4
        with:
          name: patches-1.0.3
          path: '**/*.mpp'

